### ISSUE TITLE
想咨询一些复现时遇到的问题

### ISSUE THREAD

**Issue by PolarisRisingWar** [dgliu/COLING22_CTM#1]
1. 请问CAIL small可以直接使用LADAN预处理后得到的train_processed_thulac_Legal_basis.pkl等三个文件来运行tune_parameters.py吗？ （另外想问一下，args.grid中的cnn指的是什么呢？） 
2. 请问config/mpbfn.yml这个文件是否应该提供呢？我没看到GitHub文件夹中有这个文件。

**Comment by dgliu** [comment]
你好，

1. CAIL small可以使用LADAN预处理后得到的数据文件，但是你需要在tune_parameters.py中重新指定-t, -v, -e的正确前缀，或者将上述数据文件改成我们默认的前缀。但是，我更建议你在datax/small中放置原始数据后，按照Usage的步骤自己重新进行生成实验数据。

2. cnn是指训练基于cnn的模型 (Table 3的分析实验中涉及)。因为它需要使用不同数据结构的文件 (w/o _Legal_basis)，所以进行了额外的判断，并不影响CTM的执行。

3. config/mpbfn.yml是在执行MPBFN时才会调用的配置文件。由于我们目前只计划提供我们CTM的实现，因此你可以参照Usage的说明来进行CTM的执行。

如果有其他的问题，请随时邮件与我联系。
