### ISSUE TITLE
请问是直接从测试集上获取category_labels的吗？

### ISSUE THREAD

**Issue by hecongqing** [dgliu/COLING22_CTM#10]
您好，
 请教下您的论文引入category_labels作为辅助标签区分legal cases是long还是tail, 阅读了您的代码发下：
在训练集、验证集、测试集通过get_category_label该函数获取category_labels，验证集、测试集通过该函数获取是否合理？
```
    def get_category_label(self, law_labels_input, accu_labels_input):
        length = len(law_labels_input)
        category_label = np.ones(length)
        count_tail = 0
        for i in range(length):
            if law_labels_input[i] in self._tail_law_index or accu_labels_input[i] in self._tail_accu_index:
                category_label[i] = 0
                count_tail += 1
        print('The total number of long tail cases is: ', count_tail)
        return category_label.tolist()

```

![image](https://github.com/dgliu/COLING22_CTM/assets/19923817/0c7cc816-2265-4dec-a5a0-c1166c32550e)

![image](https://github.com/dgliu/COLING22_CTM/assets/19923817/274e2ee6-8408-47af-9eb8-eebbfe2e0c3a)

**Comment by dgliu** [comment]
你好，我们当时在项目中实验和比较了两种评估方式，且当前只提供了其中一种。

- 由于考虑到在实际使用中可以同时利用head和tail输出两个结果，从业者通常可以区分出case的频率属性且进行两个结果的合理比较，因此第一种评估方式如你所指出的。

- 进一步地，第二种评估方式为使用predic_category来区分结果，由于在训练过程中频率属性区分的任务准确率较高，因此尽管可能会损失一小部分性能，但是也在一个可接受的范围内。

**Comment by hecongqing** [comment]
如果真实的category_labels，可能会存在数据穿越的问题，因为实际上测试集我们是无法知道每个数据的分布。感觉用predic_category来预测分布，进而区分long或者tail的结果更好一点

**Comment by dgliu** [comment]
> 如果真实的category_labels，可能会存在数据穿越的问题，因为实际上测试集我们是无法知道每个数据的分布。感觉用predic_category来预测分布，进而区分long或者tail的结果更好一点

是的，后者更加准确，前者侧重实际使用的角度。我昨天已经更新了代码，增加了对后者的示例。

**Comment by hecongqing** [comment]
nice work
