### ISSUE TITLE
分享一些在CAIL经LADAN式预处理后得到数据上进行复现后的解决方案

### ISSUE THREAD

**Issue by PolarisRisingWar** [dgliu/COLING22_CTM#2]
首先说明一下，我只会用PyTorch，不会用TensorFlow……

修改文件名就不写了，我是直接用`{mode}_processed_thulac_Legal_basis.pkl`实现的。其他需要改的地方：第一是代码里直接写死了法条和罪名标签的数目，这个需要手动改；第二是id.py文件第449行需要改成`return yaml.safe_load(stream)[key]`，好像是因为`yaml.load()`函数有什么更新；第三是因为我出现了OOM问题，单修改CTM.py的87行`batch_size`默认值之后还会出现RNN维度不匹配的问题，我因为不知道别的连锁的地方在哪，所以直接把各种128都改成64了，config/GCN.config的第44行改成`output_time = 64`，CTM.py第49行改成`lstm_size = trial.suggest_categorical('lstm_size', [64])`、第77行改成`search_space = {"lstm_size": [64]}`；第四是我用reproduce_paper_results.py输出的结果作为最终指标的，第12行改成`method_list = ['CTM']`，第29行改成`for s in range(1):`第五是CAIL-big本身没有验证集，所以我随机抽取1/10训练集作为验证集（我看代码里似乎本来也是差不多这么处理的）。

small和big都能跑出来，结果是合理的。

**Comment by PolarisRisingWar** [comment]
另外我写了论文阅读笔记：[Re 39：读论文 CTM Augmenting Legal Judgment Prediction with Contrastive Case Relations](https://blog.csdn.net/PolarisRisingWar/article/details/127515132)

**Comment by dgliu** [comment]
Hi, 感谢你细致的分享！

1) 由于LADAN的处理移除了低频样本，因此需要有一个不一样的数目设置；
2) yaml的版本问题；
3) 我们在实验中使用了40G内存的GPU，我们后续会对代码进行完善以便于同步设置batch_size

我们自己重新进行了数据处理的原因其实有两点：第一点是由于我们的问题设置，所以低频样本不能被过滤掉；第二点在于先前的工作尽管描述了类似的数据处理过程，但是在报告的数据统计上并不统一。

因此我们希望对其进行验证，采用了类似LADAN的处理方式，所以复用LADAN的预处理文件并不需要太多的修改。此外，在我们前期的数据探索中发现，先前的工作都忽略了对重复样本的移除。但是为了尽可能保证与它们的一致性，我们也没有执行这个过程，但是在代码中提供了相应的接口。

最后，我在阅读笔记中看到你可能对论文中的某些表述存在疑惑。如有需要，你可以通过邮件提供你的联系方式，以便我们可以进一步的讨论。

**Comment by PolarisRisingWar** [comment]
好的，非常感谢，我的微信号也是PolarisRisingWar，昵称是诸神缄默不语
