### ISSUE TITLE
关于predic_law_的计算

### ISSUE THREAD

**Issue by wq55** [dgliu/COLING22_CTM#4]
作者你好，我想问一下计算predic_law_ = predic_law_head_ * y_category_ + predic_law_tail_ * (1 - y_category_)时，为什么y_category_ 用的是真实标签，而不用预测出的predic_category进行计算

**Comment by dgliu** [comment]
你好，感谢你有价值的提问。
-由于我们考虑在实际使用中可以同时利用head和tail输出两个结果，从业者较为容易区分出case的频率属性和进行两个结果的比较，所以最后采用了y_category_。
-但是，你仍可以使用predic_category进行替代，由于在训练过程中频率属性区分的任务准确率较高，因此尽管可能会损失一部分性能，但是也在一个可接受的范围内。
谢谢。

**Comment by wq55** [comment]
多谢解答！
