### ISSUE TITLE
关于test的问题

### ISSUE THREAD

**Issue by zzhiyun** [dgliu/COLING22_CTM#6]
作者您好，这边读了您的代码以后我有一个疑问，如果我没有理解错误的话，您在训练模型的代码中是在每个epoch后都在test_set上进行了模型的评估对吗？那么请问一下这样会不会对模型的最后结果造成影响？谢谢

**Comment by dgliu** [comment]
你好，

在训练过程中对验证和测试集同时进行预测输出和评估只是为了便于观察不同超参数组合下的训练收敛情况。
由于不涉及到模型参数的更新，这些过程并不会对模型的最后结果产生什么影响。
