### ISSUE TITLE
some problem with data file

### ISSUE THREAD

**Issue by moshushi007ow** [dgliu/COLING22_CTM#7]
Hello,  how to obtain or generate the w2id_thulac.pkl file (and other similar files) which appears in line 11 of the generate_data_structure.py file. Thank you very much.
![image](https://github.com/dgliu/COLING22_CTM/assets/65228227/fdae374c-b462-4e95-900c-12ad3713be9f)

**Comment by dgliu** [comment]
Hi, you can obtain these dependency files required for data generation from [LADAN's open-source library](https://github.com/prometheusXN/LADAN/tree/master/data_and_config).

**Comment by dgliu** [comment]
> Hello, how to obtain or generate the w2id_thulac.pkl file (and other similar files) which appears in line 11 of the generate_data_structure.py file. Thank you very much. ![image](https://private-user-images.githubusercontent.com/65228227/296244242-fdae374c-b462-4e95-900c-12ad3713be9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDI5NjAsIm5iZiI6MTcwNTI0MjY2MCwicGF0aCI6Ii82NTIyODIyNy8yOTYyNDQyNDItZmRhZTM3NGMtYjQ2Mi00ZTk1LTkwMGMtMTJhZDM3MTNiZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE0MzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YzBmZjJlMGZjMWU3ZGFiZmM3ODM0YTM2NDljYzE4Yjc4ZjFiNTBhY2Q3NDJjNTc2MGQ3MjU5Y2Y0MWRhY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bgiPerxoTjQkKrmEtXTSVvsIYdHpWoDU1mv-GUoXdUs)

Hi, you can obtain these dependency files required for data generation from [LADAN's open-source library](https://github.com/prometheusXN/LADAN/tree/master/data_and_config).

**Comment by moshushi007ow** [comment]
> > Hello, how to obtain or generate the w2id_thulac.pkl file (and other similar files) which appears in line 11 of the generate_data_structure.py file. Thank you very much. ![image](https://private-user-images.githubusercontent.com/65228227/296244242-fdae374c-b462-4e95-900c-12ad3713be9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDI5NjAsIm5iZiI6MTcwNTI0MjY2MCwicGF0aCI6Ii82NTIyODIyNy8yOTYyNDQyNDItZmRhZTM3NGMtYjQ2Mi00ZTk1LTkwMGMtMTJhZDM3MTNiZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE0MzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YzBmZjJlMGZjMWU3ZGFiZmM3ODM0YTM2NDljYzE4Yjc4ZjFiNTBhY2Q3NDJjNTc2MGQ3MjU5Y2Y0MWRhY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bgiPerxoTjQkKrmEtXTSVvsIYdHpWoDU1mv-GUoXdUs)
> 
> Hi, you can obtain these dependency files required for data generation from [LADAN's open-source library](https://github.com/prometheusXN/LADAN/tree/master/data_and_config).

Thank you very much! But I still have a question, which may seem a bit stupid. What is the function of these files? Is it an intermediate result or a parameter of some kind of model file? Because I noticed that these files in LADAN are also provided directly instead of through Generated in some way.

**Comment by dgliu** [comment]
> > > Hello, how to obtain or generate the w2id_thulac.pkl file (and other similar files) which appears in line 11 of the generate_data_structure.py file. Thank you very much. ![image](https://private-user-images.githubusercontent.com/65228227/296244242-fdae374c-b462-4e95-900c-12ad3713be9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDI5NjAsIm5iZiI6MTcwNTI0MjY2MCwicGF0aCI6Ii82NTIyODIyNy8yOTYyNDQyNDItZmRhZTM3NGMtYjQ2Mi00ZTk1LTkwMGMtMTJhZDM3MTNiZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE0MzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YzBmZjJlMGZjMWU3ZGFiZmM3ODM0YTM2NDljYzE4Yjc4ZjFiNTBhY2Q3NDJjNTc2MGQ3MjU5Y2Y0MWRhY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bgiPerxoTjQkKrmEtXTSVvsIYdHpWoDU1mv-GUoXdUs)
> > 
> > 
> > Hi, you can obtain these dependency files required for data generation from [LADAN's open-source library](https://github.com/prometheusXN/LADAN/tree/master/data_and_config).
> 
> Thank you very much! But I still have a question, which may seem a bit stupid. What is the function of these files? Is it an intermediate result or a parameter of some kind of model file? Because I noticed that these files in LADAN are also provided directly instead of through Generated in some way.

These dependency files are prepared in advance and used to clean the data set, such as converting to IDs and removing stop words. 

Since no instructions on generating them were provided in these previous related works, I also directly used these dependency files to ensure comparability with these related works.
