### ISSUE TITLE
请问Lawformer-CTM的代码是否会公开

### ISSUE THREAD

**Issue by hecongqing** [dgliu/COLING22_CTM#8]

**Comment by dgliu** [comment]
你好，如若需要，可以提供你的邮箱地址，我会发送一份Lawformer-CTM的代码副本作为参照。

**Comment by dgliu** [comment]
> _No description provided._

你好，如若需要，可以提供你的邮箱地址，我会发送一份Lawformer-CTM的代码副本作为参照。

**Comment by hecongqing** [comment]
谢谢，  我的邮箱是  hecongqing@hotmail.com

**Comment by hecongqing** [comment]
另外，我想请问下  requirement.txt， 需要的环境

**Comment by winnerLuo** [comment]
请问Lawformer-CTM的代码是否会公开，也请发我一份requirement.txt,我的邮箱2963382776@qq.comqq.com

**Comment by dgliu** [comment]
> 谢谢， 我的邮箱是 [hecongqing@hotmail.com](mailto:hecongqing@hotmail.com)

已发送。

**Comment by dgliu** [comment]
> 请问Lawformer-CTM的代码是否会公开，也请发我一份requirement.txt,我的邮箱[2963382776@qq.comqq.com](mailto:2963382776@qq.comqq.com)

已发送。
