### ISSUE TITLE
相关代码

### ISSUE THREAD

**Issue by winnerLuo** [dgliu/COLING22_CTM#9]
Hello, could you please share the code, such as the one comparing with some baseline models? What do these files in the figure mean? Please explain their functions. Thank you!
![QQ截图20240318150349](https://github.com/dgliu/COLING22_CTM/assets/70368328/81ea3585-affa-4237-b07c-cd2128e24ad3)
![QQ截图20240318150349](https://github.com/dgliu/COLING22_CTM/assets/70368328/4d9d2b6b-2a95-46ee-9632-d3ea0ff05869)

**Comment by dgliu** [comment]
Hi,

1. To implement the baseline model, you can refer to the open-source libraries of LADAN (including MTL, TopJudge, and MPBFN) and NeurJudge.

2. |data_exploration| is used for simple analysis of data, especially the detection of duplicate instances;
|get_processed_data| is used to generate training, validation, and test sets;
|generate_data_structure| is used to generate data structures that different methods can call during training;
|tune_parameters| is used to search for hyperparameters;
|reproduce_paper_results| is used to output results based on the optimal hyperparameters.

Best,
Dugang
